# Generated by Django 6.0.5 on 2026-05-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=100)),
                ('annee_publication', models.IntegerField()),
                ('quantite_disponible', models.IntegerField()),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
    ]
