# Generated by Django 6.0.5 on 2026-05-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('reserve', 'Réservé')], max_length=20),
        ),
    ]
