# Generated by Django 6.0.5 on 2026-05-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_alter_livre_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livre',
            options={'ordering': ['titre'], 'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.AlterField(
            model_name='livre',
            name='annee_publication',
            field=models.IntegerField(verbose_name='Année de publication'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.CharField(max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='quantite_disponible',
            field=models.IntegerField(default=1, verbose_name='Quantité disponible'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='statut',
            field=models.CharField(choices=[('disponible', '✅ Disponible'), ('emprunte', '📖 Emprunté'), ('reserve', '⏳ Réservé')], default='disponible', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
